### PR TITLE
Todo 2

### PR DESCRIPTION
**Pull request by PhuNH**
Might need some improvement since one service is made only to create a folder.

### CODE REVIEW

**Comment by anuragyayhdapu** [comment]
Thanks yaar, for creating renderd service and registering it on startup.

**Comment by PhuNH** [comment]
I just pushed to my patch-2 branch, came here and saw you had merged "1 minute ago" 😅
Anyway please check the new PR

**Comment by anuragyayhdapu** [comment]
On which version of Fedora are you testing ?

**Comment by PhuNH** [comment]
I'm on version 29.

**Comment by anuragyayhdapu** [comment]
I’m downloading 30 right. In the mood for fresh install & bulletproofing
this guide for another year.

**Comment by PhuNH** [comment]
nice, have fun with that

**Pull request merged**
